module.exports = {
    // WEBSITE DEFAULT ROLES
    ADMIN: "ADMIN",
    MODERATEUR: "MODERATEUR",
    USER: "USER",

    // COMPANY DEFAULT ROLES
    COMPANY_ADMIN: "COMPANY_ADMIN",
    COMPANY_MODERATEUR: "COMPANY_MODERATEUR",
    COMPANY_USER: "COMPANY_USER",

    // PROJECT DEFAULT ROLES
    PROJECT_ADMIN: "PROJECT_ADMIN",
    PROJECT_MODERATEUR: "PROJECT_MODERATEUR",
    PROJECT_USER: "PROJECT_USER",

    // APPLICATION DEFAULT ROLES
    APPLICATION_ADMIN: "APPLICATION_ADMIN",
    APPLICATION_MODERATEUR: "APPLICATION_MODERATEUR",
    APPLICATION_USER: "APPLICATION_USER",

    // COMPONENT DEFAULT ROLES
    COMPONENT_ADMIN: "COMPONENT_ADMIN",
    COMPONENT_MODERATEUR: "COMPONENT_MODERATEUR",
    COMPONENT_USER: "COMPONENT_USER",

    // SUBCOMPONENT DEFAULT ROLES
    SUBCOMPONENT_ADMIN: "SUBCOMPONENT_ADMIN",
    SUBCOMPONENT_MODERATEUR: "SUBCOMPONENT_MODERATEUR",
    SUBCOMPONENT_USER: "SUBCOMPONENT_USER",
}